const data = {
    vocabulary: [
        { word: "Nursing", meaningAr: "التمريض" },
        { word: "Nursery", meaningAr: "حضانة" },
        { word: "Lifeguard", meaningAr: "منقذ" },
        { word: "Recover", meaningAr: "يتعافى / يشفى" },
        { word: "Never-ending", meaningAr: "مستمر / لا ينتهي" },
    ],

    expressions: [
        { word: "Emergency operator", meaningAr: "موظف الطوارئ" },
        { word: "Emergency call", meaningAr: "مكالمة طوارئ" },
        { word: "Handle emergencies", meaningAr: "يتعامل مع الحالات الطارئة" },
        { word: "Have a pain", meaningAr: "يعاني من ألم" },
        { word: "A severe pain", meaningAr: "ألم شديد" },
        { word: "A never-ending rollercoaster", meaningAr: "حالة متقلبة المشاعر" },
        { word: "Make every effort", meaningAr: "يبذل أقصى مجهود" },
        { word: "Make sure", meaningAr: "يتأكد" },
        { word: "Do first aid", meaningAr: "يقدم الإسعافات الأولية" },
        { word: "Do / perform a task", meaningAr: "يؤدي مهمة" },
        { word: "Pay attention to", meaningAr: "ينتبه إلى" },
        { word: "Give a reason why", meaningAr: "يعطي سببًا" },
        { word: "Focus (concentrate) on", meaningAr: "يركز على" },
        { word: "Trade … for", meaningAr: "يستبدل بـ" },
        { word: "Recover from", meaningAr: "يتعافى من" },
        { word: "Suffer from", meaningAr: "يعاني من" },
        { word: "Buzz with", meaningAr: "يضج بـ / يمتلئ بـ" },
        { word: "Care for", meaningAr: "يعتني بـ" },
        { word: "Move on", meaningAr: "ينتقل إلى / يتجاوز" },
        { word: "Check on", meaningAr: "يطمئن على" },
        { word: "Rely on (depend on)", meaningAr: "يعتمد على" },
        { word: "Reflect on", meaningAr: "يتأمل في / يفكر في" },
        { word: "Rush in", meaningAr: "يندفع إلى الداخل بسرعة" },
        { word: "Related to", meaningAr: "متعلق بـ" },
    ],
    
    important: [
        { word: "Beep", meaningAr: "يصدر صوت تنبيه" },
        { word: "Mental", meaningAr: "ذهني / عقلي" },
        { word: "Mentally", meaningAr: "ذهنيًا" },
        { word: "Patient", meaningAr: "مريض / صبور" },
        { word: "Chart", meaningAr: "رسم بياني / ملف" },
        { word: "Review", meaningAr: "يراجع" },
        { word: "Rush", meaningAr: "يندفع بسرعة" },
        { word: "Monitor", meaningAr: "يراقب / شاشة" },
        { word: "Task", meaningAr: "مهمة" },
        { word: "Anxious", meaningAr: "قلق" },
        { word: "Anxiously", meaningAr: "بقلق" },
        { word: "Smoothly", meaningAr: "بسلاسة" },
        { word: "Support", meaningAr: "يدعم / دعم" },
        { word: "Ensure", meaningAr: "يتأكد / يضمن" },
        { word: "Assist", meaningAr: "يساعد" },
        { word: "Trade", meaningAr: "يتاجر / تجارة" },
        { word: "Progress", meaningAr: "تقدم / يتقدم" },
        { word: "Exhausted", meaningAr: "مرهق جدًا" },
        { word: "Fulfilled", meaningAr: "راضٍ / مشبع" },
        { word: "Document", meaningAr: "يوثق / يسجل" },
        { word: "Severe", meaningAr: "شديد / خطير" },
        { word: "Surgery", meaningAr: "عملية جراحية" },
        { word: "Surgeon", meaningAr: "جرّاح" },
        { word: "Surgical", meaningAr: "جراحي" },
        { word: "Elderly", meaningAr: "مسن / عجوز" },
        { word: "Contaminated", meaningAr: "ملوث" },
        { word: "Comfort", meaningAr: "راحة / يواسي" },
        { word: "Qualities", meaningAr: "صفات / مميزات" },
        { word: "Emergency", meaningAr: "حالة طوارئ" },
        { word: "Critical", meaningAr: "حرج / خطير" },
        { word: "Healthcare", meaningAr: "الرعاية الصحية" },
        { word: "Safety", meaningAr: "أمان / سلامة" },
        { word: "Typical", meaningAr: "نموذجي / تقليدي" },
        { word: "Look like", meaningAr: "يبدو مثل" },
        { word: "Preparation", meaningAr: "تحضير / استعداد" },
        { word: "Dizzy", meaningAr: "يشعر بالدوار" },
        { word: "Witness", meaningAr: "شاهد / يشهد" },
        { word: "Duties", meaningAr: "واجبات" },
        { word: "Lip", meaningAr: "شفّة" },
        { word: "Collect", meaningAr: "يجمع" },
        { word: "Neighbour", meaningAr: "جار" },
    ],
};

export default data;
