const data = {
    vocabulary: [
        { word: "Colleague", meaningAr: "زميل عمل" },
        { word: "Medication", meaningAr: "دواء / علاج" },
        { word: "Pulse", meaningAr: "نبض" },
        { word: "Paramedics", meaningAr: "المسعفون" },
        { word: "Roller-coaster", meaningAr: "تجربة مثيرة بالمشاعر المتقلبة" },
        { word: "Conscious", meaningAr: "واعٍ / مدرك" },
        { word: "Chest", meaningAr: "الصدر" },
        { word: "Victim", meaningAr: "الضحية" },
        { word: "Challenge", meaningAr: "تحدي / يتحدى" },
        { word: "CPR", meaningAr: "الإنعاش القلبي الرئوي" },
        { word: "Nursing", meaningAr: "التمريض" },
        { word: "Nursery", meaningAr: "حضانة" },
        { word: "Lifeguard", meaningAr: "منقذ" },
        { word: "Never-ending", meaningAr: "مستمر" },
        { word: "Recover", meaningAr: "يتعافى / يشفي" },
        { word: "Steady", meaningAr: "ثابت / مستقر" },
        { word: "Shout", meaningAr: "يصرخ" },
        { word: "Examine", meaningAr: "يفحص / يعاين" },
        { word: "Collarbone", meaningAr: "عظمة الترقوة" },
        { word: "Temperature", meaningAr: "درجة الحرارة" },
        { word: "Analyze", meaningAr: "يحلل" },
        { word: "Antiseptic", meaningAr: "مطهر" },
        { word: "Remove", meaningAr: "يزيل / ينزع" },
        { word: "Grasp", meaningAr: "يمسك / يفهم جيداً" },
        { word: "Miserable", meaningAr: "بائس" },
        { word: "Treatment", meaningAr: "علاج / معالجة" },
        { word: "Condition", meaningAr: "حالة / وضع" },
        { word: "Cough", meaningAr: "كحة / يسعل" },
        { word: "Stethoscope", meaningAr: "سماعة طبيب" },
        { word: "Prescription", meaningAr: "روشتة" },
        { word: "Forehead", meaningAr: "جبهة" },
        { word: "Urgent", meaningAr: "عاجل" },
        { word: "Urgency", meaningAr: "إلحاح / استعجال" },
        { word: "Symptoms", meaningAr: "أعراض" },
        { word: "Stitch", meaningAr: "غرزة / يخيط" },
        { word: "Experience", meaningAr: "خبرة / يمر بتجربة" },
        { word: "Experiment", meaningAr: "يجرب / تجربة علمية" },
        { word: "Director", meaningAr: "مدير / مخرج" },
        { word: "State", meaningAr: "يصرح / حالة" }
    ],

    expressions: [
        { word: "Emergency operator", meaningAr: "موظف الطوارئ" },
        { word: "Emergency call", meaningAr: "مكالمة طوارئ" },
        { word: "Handle emergencies", meaningAr: "يتعامل مع الحالات الطارئة" },
        { word: "A severe pain", meaningAr: "ألم شديد" },
        { word: "Have a pain", meaningAr: "يعاني من ألم" },
        { word: "A never-ending rollercoaster", meaningAr: "رحلة متقلبة مستمرة" },
        { word: "Make every effort", meaningAr: "يبذل أقصى جهد" },
        { word: "Make sure", meaningAr: "يتأكد" },
        { word: "Do first aid", meaningAr: "يقوم بالإسعافات الأولية" },
        { word: "Do / perform a task", meaningAr: "يؤدي مهمة" },
        { word: "Pay attention to", meaningAr: "ينتبه لـ" },
        { word: "Give a reason why", meaningAr: "يعطي سبب" },
        { word: "Focus (concentrate) on", meaningAr: "يركز على" },
        { word: "Trade … for", meaningAr: "يستبدل بـ" },
        { word: "Recover from", meaningAr: "يتعافى من" },
        { word: "Suffer from", meaningAr: "يعاني من" },
        { word: "Buzz with", meaningAr: "يضج بـ / يمتلئ بـ نشاط" },
        { word: "Care for", meaningAr: "يعتني بـ" },
        { word: "Move on", meaningAr: "ينتقل إلى / يتجاوز" },
        { word: "Check on", meaningAr: "يتفقد / يطمئن على" },
        { word: "Rely on (depend on)", meaningAr: "يعتمد على" },
        { word: "Reflect on", meaningAr: "يتأمل في / يفكر في" },
        { word: "Rush in", meaningAr: "يندفع إلى الداخل بسرعة" },
        { word: "Related to", meaningAr: "متعلق بـ" },
        { word: "A medical emergency", meaningAr: "حالة طبية طارئة" },
        { word: "Emergency room (ER)", meaningAr: "غرفة الطوارئ" },
        { word: "Be in full", meaningAr: "في كامل الطاقة" },
        { word: "Fill with", meaningAr: "يملأ بـ" },
        { word: "Full of", meaningAr: "مليء بـ" },
        { word: "Fly open", meaningAr: "ينفتح فجأة" },
        { word: "A deep cut on", meaningAr: "جرح عميق على" },
        { word: "Come to an end", meaningAr: "ينتهي" },
        { word: "A construction worker", meaningAr: "عامل بناء" },
        { word: "Be proud of / Take pride in", meaningAr: "يفخر بـ" },
        { word: "Weep with relief", meaningAr: "يبكي من الارتياح" },
        { word: "Give instructions", meaningAr: "يعطي تعليمات" },
        { word: "Get worse", meaningAr: "يسوء" },
        { word: "Have a cough", meaningAr: "يعاني من كحة" },
        { word: "Have a headache", meaningAr: "يعاني من صداع" },
        { word: "Have a cold", meaningAr: "يعاني من نزلة برد" },
        { word: "Make an appointment", meaningAr: "يحدد موعداً" },
        { word: "Feel better", meaningAr: "يشعر بتحسن" },
        { word: "Give a prescription", meaningAr: "يعطي وصفة" },
        { word: "Face problems", meaningAr: "يواجه المشاكل" },
        { word: "Under the weather", meaningAr: "يشعر بالتعب" },
        { word: "Take over", meaningAr: "يتولى / يستحوذ على" },
        { word: "Clean up", meaningAr: "ينظف / يرتب" },
        { word: "Cry out", meaningAr: "يصرخ" },
        { word: "Run into", meaningAr: "يصطدم بـ / يقابل صدفة" },
        { word: "Covered in", meaningAr: "مغطى بـ" }
    ],

    important: [
        { word: "Beep", meaningAr: "تطلق صوت تنبيه / يصفر" },
        { word: "Mentally", meaningAr: "ذهنياً / عقلياً" },
        { word: "Chart", meaningAr: "رسم بياني / مخطط / شَفَة" },
        { word: "Rush", meaningAr: "يندفع بسرعة / يسرع" },
        { word: "Task", meaningAr: "مهمة / واجب" },
        { word: "Anxiously", meaningAr: "بقلق / بتوتر" },
        { word: "Support", meaningAr: "يدعم / دعم" },
        { word: "Assist", meaningAr: "يساعد" },
        { word: "Progress", meaningAr: "تقدم / يحرز تقدماً" },
        { word: "Fulfilled", meaningAr: "راضٍ / مُشْبَع بالإنجاز" },
        { word: "Document", meaningAr: "يوثق / يسجل" },
        { word: "Surgery", meaningAr: "عملية جراحية" },
        { word: "Surgical", meaningAr: "جراحي" },
        { word: "Contaminated", meaningAr: "ملوث" },
        { word: "Qualities", meaningAr: "صفات / مميزات" },
        { word: "Critical", meaningAr: "حرج / خطير" },
        { word: "Safety", meaningAr: "أمان / سلامة" },
        { word: "Look like", meaningAr: "يبدو مثل / يشبه" },
        { word: "Dizzy", meaningAr: "يشعر بالدوار" },
        { word: "Duties", meaningAr: "واجبات" },
        { word: "Collect", meaningAr: "يجمع" },
        { word: "Mental", meaningAr: "عقلي / ذهني" },
        { word: "Patient", meaningAr: "مريض / صبور" },
        { word: "Review", meaningAr: "يراجع / يُقَيِّم" },
        { word: "Monitor", meaningAr: "يراقب / شاشة" },
        { word: "Anxious", meaningAr: "متوتر / قلق" },
        { word: "Smoothly", meaningAr: "بسلاسة / بسهولة" },
        { word: "Ensure", meaningAr: "يضمن / يتأكد من" },
        { word: "Trade", meaningAr: "يتاجر / تجارة / تبادل" },
        { word: "Exhausted", meaningAr: "مرهق جداً / مُنْهَك" },
        { word: "Reflect on", meaningAr: "يتأمل / يفكر بعمق" },
        { word: "Severe", meaningAr: "شديد / خطير" },
        { word: "Surgeon", meaningAr: "جراح" },
        { word: "Elderly", meaningAr: "مسن / عجوز" },
        { word: "Comfort", meaningAr: "راحة / يُواسي" },
        { word: "Emergency", meaningAr: "حالة طوارئ" },
        { word: "Healthcare", meaningAr: "الرعاية الصحية" },
        { word: "Typical", meaningAr: "نموذجي / تقليدي" },
        { word: "Preparation", meaningAr: "تحضير / استعداد" },
        { word: "Witness", meaningAr: "يشاهد / يشهد" },
        { word: "Lip", meaningAr: "شَفَة" },
        { word: "Neighbour", meaningAr: "جار" },
        { word: "Relief", meaningAr: "راحة / ارتياح" },
        { word: "Tears", meaningAr: "دموع" },
        { word: "Blood", meaningAr: "دم" },
        { word: "Bleeding", meaningAr: "نزيف" },
        { word: "Flexible", meaningAr: "مرن" },
        { word: "Member", meaningAr: "عضو" },
        { word: "Hesitation", meaningAr: "تردد" },
        { word: "Staff", meaningAr: "طاقم عمل" },
        { word: "Perform", meaningAr: "يؤدي / يقوم بـ" },
        { word: "Construction", meaningAr: "بناء / إنشاء" },
        { word: "Remind", meaningAr: "يذكر / ينبه" },
        { word: "Operation", meaningAr: "عملية جراحية" },
        { word: "Instructions", meaningAr: "تعليمات" },
        { word: "Hand", meaningAr: "يعطي / يسلم" },
        { word: "Technician", meaningAr: "فني تقني" },
        { word: "Wipe", meaningAr: "يمسح / منديل" },
        { word: "Throat", meaningAr: "حنجرة / حلق" },
        { word: "Clinic", meaningAr: "عيادة" },
        { word: "Sterile", meaningAr: "معقم / خالٍ من الجراثيم" },
        { word: "Event", meaningAr: "حدث / واقعة" },
        { word: "Value", meaningAr: "قيمة / يقدر" },
        { word: "Confident", meaningAr: "واثق" },
        { word: "Injured", meaningAr: "مصاب / مجروح" },
        { word: "Sacrifice", meaningAr: "تضحية / يضحي" },
        { word: "Toddler", meaningAr: "طفل صغير" },
        { word: "Crash", meaningAr: "حادث / تصادم" },
        { word: "Emotionally", meaningAr: "عاطفياً" },
        { word: "Serious", meaningAr: "خطير / جاد" }
    ],

    Idioms: [
        { word: "Spring into action", meaningAr: "يتحرك فوراً" },
        { word: "No pain, no gain", meaningAr: "لا نجاح بدون تعب" },
        { word: "Sweat blood", meaningAr: "يبذل مجهود ضخم" },
        { word: "Burn the midnight oil", meaningAr: "يسهر للعمل في وقت متأخر" },
        { word: "Hit the ground running", meaningAr: "يبدأ العمل بحماس" },
        { word: "Go the extra mile", meaningAr: "يبذل جهد إضافي" },
        { word: "Makes the dream work", meaningAr: "يجعل الحلم ممكناً" },
        { word: "Rain cats and dogs", meaningAr: "تمطر بغزارة" },
        { word: "Soaked to the skin", meaningAr: "مبتل تماماً" },
        { word: "Jump into action", meaningAr: "يبدأ العمل بسرعة" },
        { word: "Pale as a ghost", meaningAr: "شاحب كالاشباح (خائف / مريض)" },
        { word: "Calm under pressure", meaningAr: "هادئ تحت الضغط" },
        { word: "Calm slowly returned", meaningAr: "الهدوء عاد تدريجياً" },
        { word: "Under the weather", meaningAr: "مريض قليلاً / ليس على ما يرام" },
        { word: "Come to an end", meaningAr: "ينتهي" },
        { word: "Break a leg", meaningAr: "حظًا سعيدًا" },
        { word: "Get a head up", meaningAr: "تنبيه مسبق / اعلم مسبقًا" },
        { word: "Get a move on", meaningAr: "استعجل / تحرك بسرعة" }
    ]
};

export default data;