const data = {
    vocabulary: [
        { word: "drivers", meaningAr: "برامج تشغيل" },
        { word: "troubleshoot", meaningAr: "استكشاف الأخطاء وإصلاحها" },
        { word: "version", meaningAr: "إصدار" },
        { word: "cotton gin", meaningAr: "آلة حلج القطن" },
        { word: "urgency", meaningAr: "إلحاح" },
        { word: "infrastructure", meaningAr: "البنية التحتية" },
        { word: "artifacts", meaningAr: "قطع أثرية" },
        { word: "initiative", meaningAr: "مبادرة" },
        { word: "serve", meaningAr: "يخدم" },
        { word: "viewpoint", meaningAr: "وجهة نظر" },
        { word: "risk", meaningAr: "خطر" },
        { word: "Laborer", meaningAr: "عامل" },
        { word: "warn", meaningAr: "يحذر" },
        { word: "explain", meaningAr: "يفسر / يشرح" },
        { word: "illness", meaningAr: "مرض" },
        { word: "Command", meaningAr: "يأمر / أمر" },
        { word: "order", meaningAr: "يأمر / أمر" },
        { word: "turn off", meaningAr: "يطفئ" },
        { word: "Supervisor", meaningAr: "مشرف / مسئول" },
        { word: "Purpose", meaningAr: "غرض / هدف" },
        { word: "benefit", meaningAr: "فائدة / يستفيد" },
        { word: "rule", meaningAr: "يحكم / حكم" },
        { word: "summarize", meaningAr: "يلخص" },
        { word: "mention", meaningAr: "يذكر" },
        { word: "warning", meaningAr: "تحذير" },
        { word: "detect", meaningAr: "يكتشف / يتعرف على" },
        { word: "solar energy", meaningAr: "الطاقة الشمسية" },
        { word: "request", meaningAr: "طلب / يطلب" },
        { word: "turn on", meaningAr: "يشغل" },
        { word: "seatbelt", meaningAr: "حزام الأمان" },
        { word: "Process", meaningAr: "عملية / خطوات" },
        { word: "Precautions", meaningAr: "احتياطات" },
        { word: "instructions", meaningAr: "تعليمات" },
        { word: "respect", meaningAr: "يحترم / احترام" },
        { word: "separate", meaningAr: "يفصل" },
        { word: "shape", meaningAr: "يشكل / شكل" },
        { word: "smooth", meaningAr: "ناعم / سلس" },
        { word: "steam engine", meaningAr: "محرك بخاري" },
        { word: "support", meaningAr: "يدعم / دعم" },
        { word: "technician", meaningAr: "فني" },
        { word: "transportation", meaningAr: "نقل" },
        { word: "urgent", meaningAr: "عاجل" },
        { word: "worry", meaningAr: "يقلق / قلق" },
        { word: "scan", meaningAr: "يمسح ضوئياً" },
        { word: "settings", meaningAr: "إعدادات" },
        { word: "smart", meaningAr: "ذكي" },
        { word: "solar-powered", meaningAr: "يعمل بالطاقة الشمسية" },
        { word: "structure", meaningAr: "هيكل" },
        { word: "technical", meaningAr: "تقني" },
        { word: "tools", meaningAr: "أدوات" },
        { word: "wonders", meaningAr: "عجائب" }
    ],

    important: [
        { word: "achieve", meaningAr: "يحقق" },
        { word: "agriculture", meaningAr: "الزراعة" },
        { word: "ancient", meaningAr: "قديم جدًا" },
        { word: "argue", meaningAr: "يجادل" },
        { word: "belief", meaningAr: "اعتقاد" },
        { word: "blend", meaningAr: "يمزج" },
        { word: "cables", meaningAr: "كابلات" },
        { word: "click", meaningAr: "يضغط / نقرة" },
        { word: "computerized", meaningAr: "محوسب" },
        { word: "craft", meaningAr: "حرفة / يصنع" },
        { word: "device", meaningAr: "جهاز" },
        { word: "disappear", meaningAr: "يختفي" },
        { word: "era", meaningAr: "عصر" },
        { word: "expert", meaningAr: "خبير" },
        { word: "fascinating", meaningAr: "مثير" },
        { word: "generation", meaningAr: "جيل" },
        { word: "historian", meaningAr: "مؤرخ" },
        { word: "human skills", meaningAr: "مهارات بشرية" },
        { word: "industrial", meaningAr: "صناعي" },
        { word: "innovation", meaningAr: "ابتكار" },
        { word: "irrigation", meaningAr: "ري" },
        { word: "loose", meaningAr: "مفكوك" },
        { word: "machinery", meaningAr: "آلات" },
        { word: "masters", meaningAr: "أساتذة" },
        { word: "monumental", meaningAr: "ضخم جدًا" },
        { word: "necessary", meaningAr: "ضروري" },
        { word: "operate", meaningAr: "يشغل" },
        { word: "preserve", meaningAr: "يحافظ على" },
        { word: "productivity", meaningAr: "إنتاجية" },
        { word: "renewable", meaningAr: "متجدد" },
        { word: "revolution", meaningAr: "ثورة" },
        { word: "role", meaningAr: "دور" },
        { word: "require", meaningAr: "يتطلب" }
    ],

    expressions: [
        { word: "as much as possible", meaningAr: "بقدر الإمكان" },
        { word: "ways of life", meaningAr: "طرق الحياة" },
        { word: "basic tools", meaningAr: "أدوات أساسية" },
        { word: "advanced machinery", meaningAr: "آلات متطورة" },
        { word: "traditional crafts", meaningAr: "الحرف التقليدية" },
        { word: "artificial intelligence", meaningAr: "الذكاء الاصطناعي" },
        { word: "play a role in", meaningAr: "يلعب دورًا في" },
        { word: "make progress", meaningAr: "يحرز تقدمًا" },
        { word: "compare with", meaningAr: "يقارن بـ" },
        { word: "import from", meaningAr: "يستورد من" },
        { word: "connect with", meaningAr: "يربط بـ" },
        { word: "replace with", meaningAr: "يستبدل بـ" },
        { word: "take over", meaningAr: "يستولي على / يسيطر" },
        { word: "worry about", meaningAr: "يقلق بشأن" },
        { word: "depend on / rely on", meaningAr: "يعتمد على" },
        { word: "From the moment", meaningAr: "من اللحظة" },
        { word: "join a meeting", meaningAr: "ينضم لاجتماع" },
        { word: "not the other way around", meaningAr: "وليس العكس" },
        { word: "shaped by", meaningAr: "يتم تشكيله بواسطة" },
        { word: "take ... to ...", meaningAr: "يأخذ إلى" },
        { word: "monitored by", meaningAr: "يُراقب بواسطة" },
        { word: "in charge of", meaningAr: "مسؤول عن" },
        { word: "daily routine", meaningAr: "الروتين اليومي" },
        { word: "Come to a standstill", meaningAr: "يتوقف تماماً" },
        { word: "powered by", meaningAr: "تعمل بفضل" },
        { word: "Part of", meaningAr: "جزء من" },
        { word: "struggle to + inf", meaningAr: "يكافح لـ" }
    ],

    idioms: [
        { word: "lay the groundwork", meaningAr: "يمهد الطريق" },
        { word: "full steam ahead", meaningAr: "ينطلق بأقصى سرعة" }
    ]
};

export default data;
